app:
  dev-admin:
    username: admin
    password: 1234
    enabled: true

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
      open-in-view: false

  liquibase:
    enabled: true

logging:
  level:
    liquibase: info
