spring:
  application:
    name: bank-rest
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml

app:
  dev-admin:
    username: admin
    password: 1234
    enabled: true